### ISSUE TITLE
Security alarm

### ISSUE THREAD

**Issue by antonfefilov** [ricardovsilva/twitter-rubyOnRails#2]
The last, but not the list issue. You should exclude config/database.yml from SCM as now we all know your database's root password. Or use dotenv gem to set ENV vars.

**Comment by ricardovsilva** [comment]
Yes, I saw this yestarday, thanks for warning. But this password is one weak password mine (I NEVER use it in production, is only to not let the default password into development environment), and this password isn't used for nothing more. But thanks for advise.
There's any way to change this and exclude from any commit of git?

**Comment by antonfefilov** [comment]
Sure, just add to your `.gitignore` file this line: `config/database.yml`

**Comment by ricardovsilva** [comment]
Added, thanks for warning.

**Comment by antonfefilov** [comment]
Ok.
